In [ ]:
import pandas as pd

kto_201901 = pd.read_excel('kto_201901.xlsx',
                           header = 1,
                           usecols = 'A:G',
                           skipfooter=4)

In [ ]:
kto_201901.head()

     국적      관광     상용    공용  유학/연수      기타       계
0  아시아주  765082  10837  1423  14087  125521  916950
1    일본  198805   2233   127    785    4576  206526
2    대만   86393     74    22    180    1285   87954
3    홍콩   34653     59     2     90    1092   35896
4   마카오    2506      2     0     17      45    2570

In [ ]:
kto_201901.tail()

         국적   관광   상용  공용  유학/연수     기타      계
62  아프리카 기타  768  718  90    206    908   2690
63     기타대륙   33    4   0      1     16     54
64     국적미상   33    4   0      1     16     54
65     교포소계    0    0   0      0  15526  15526
66       교포    0    0   0      0  15526  15526

In [ ]:
kto_201901.describe()

                 관광            상용  ...             기타              계
count      67.00000     67.000000  ...      67.000000      67.000000
mean    26396.80597    408.208955  ...    5564.208955   32979.194030
std    102954.04969   1416.040302  ...   17209.438418  122821.369969
min         0.00000      0.000000  ...      16.000000      54.000000
25%       505.00000     14.500000  ...     260.000000     927.000000
50%      1304.00000     45.000000  ...     912.000000    2695.000000
75%      8365.00000    176.500000  ...    2824.500000   14905.500000
max    765082.00000  10837.000000  ...  125521.000000  916950.000000

[8 rows x 6 columns]

In [ ]:
condition = ((kto_201901['관광'] == 0) | (kto_201901['상용'] == 0) | (kto_201901['공용'] == 0) | (kto_201901['유학/연수'] == 0))

kto_201901[condition]

        국적    관광   상용  공용  유학/연수     기타      계
4      마카오  2506    2   0     17     45   2570
20    이스라엘   727   12   0      9     57    805
22  우즈베키스탄  1958  561   0    407   2828   5754
38     스위스   613   18   0     19     97    747
45     그리스   481   17   4      0    273    775
46    포르투갈   416   14   0     13    121    564
51   크로아티아   226   12   0      3    250    491
54     폴란드   713   10   0     27    574   1324
59  대양주 기타   555    3   4      0     52    614
63    기타대륙    33    4   0      1     16     54
64    국적미상    33    4   0      1     16     54
65    교포소계     0    0   0      0  15526  15526
66      교포     0    0   0      0  15526  15526

In [ ]:
kto_201901['기준연월'] = '2019-01'

In [ ]:
kto_201901.head()

     국적      관광     상용    공용  유학/연수      기타       계     기준연월
0  아시아주  765082  10837  1423  14087  125521  916950  2019-01
1    일본  198805   2233   127    785    4576  206526  2019-01
2    대만   86393     74    22    180    1285   87954  2019-01
3    홍콩   34653     59     2     90    1092   35896  2019-01
4   마카오    2506      2     0     17      45    2570  2019-01

In [ ]:
kto_201901['국적'].unique()

array(['아시아주', '일본', '대만', '홍콩', '마카오', '태국', '말레이시아', '필리핀', '인도네시아',
       '싱가포르', '미얀마', '베트남', '인도', '스리랑카', '파키스탄', '방글라데시', '캄보디아', '몽골',
       '중국', '이란', '이스라엘', '터키', '우즈베키스탄', '카자흐스탄', 'GCC', '아시아 기타', '미주',
       '미국', '캐나다', '멕시코', '브라질', '미주 기타', '구주', '영국', '독일', '프랑스',
       '네덜란드', '스웨덴', '스위스', '이탈리아', '덴마크', '노르웨이', '벨기에', '오스트리아', '스페인',
       '그리스', '포르투갈', '핀란드', '아일랜드', '우크라이나', '러시아', '크로아티아', '루마니아',
       '불가리아', '폴란드', '구주 기타', '대양주', '오스트레일리아', '뉴질랜드', '대양주 기타',
       '아프리카주', '남아프리카공화국', '아프리카 기타', '기타대륙', '국적미상', '교포소계', '교포'],
      dtype=object)

In [ ]:
continents_list = ['아시아주','미주','구주','대양주','아프리카주','기타대륙','교포소계']

In [ ]:
condition = (kto_201901.국적.isin(continents_list) == False)
kto_201901_country = kto_201901[condition]
kto_201901_country['국적'].unique()

array(['일본', '대만', '홍콩', '마카오', '태국', '말레이시아', '필리핀', '인도네시아', '싱가포르',
       '미얀마', '베트남', '인도', '스리랑카', '파키스탄', '방글라데시', '캄보디아', '몽골', '중국',
       '이란', '이스라엘', '터키', '우즈베키스탄', '카자흐스탄', 'GCC', '아시아 기타', '미국',
       '캐나다', '멕시코', '브라질', '미주 기타', '영국', '독일', '프랑스', '네덜란드', '스웨덴',
       '스위스', '이탈리아', '덴마크', '노르웨이', '벨기에', '오스트리아', '스페인', '그리스', '포르투갈',
       '핀란드', '아일랜드', '우크라이나', '러시아', '크로아티아', '루마니아', '불가리아', '폴란드',
       '구주 기타', '오스트레일리아', '뉴질랜드', '대양주 기타', '남아프리카공화국', '아프리카 기타',
       '국적미상', '교포'], dtype=object)

In [ ]:
kto_201901_country

          국적      관광    상용    공용  유학/연수     기타       계     기준연월
1         일본  198805  2233   127    785   4576  206526  2019-01
2         대만   86393    74    22    180   1285   87954  2019-01
3         홍콩   34653    59     2     90   1092   35896  2019-01
4        마카오    2506     2     0     17     45    2570  2019-01
5         태국   34004    37   199     96   6998   41334  2019-01
6      말레이시아   19043    95     7     99   2821   22065  2019-01
7        필리핀   14279   211   161    184  15638   30473  2019-01
8      인도네시아   14183   136    38    187   4298   18842  2019-01
9       싱가포르    8372    94     8     48   1333    9855  2019-01
10       미얀마    1304    10    31     67   3877    5289  2019-01
11       베트남   10739   763   110   1667   6904   20183  2019-01
12        인도    2318  2656    46    177   3474    8671  2019-01
13      스리랑카     157    54     5     28   1043    1287  2019-01
14      파키스탄     238   178    10    193    413    1032  2019-01
15     방글라데시     149   126    27     97    848    1247  2019-01
16      캄보디아     635    39    55     51   1915    2695  2019-01
17        몽골    8358    77   304    484    562    9785  2019-01
18        중국  320113  2993   138   8793  60777  392814  2019-01
19        이란      60    45    10     23     46     184  2019-01
20      이스라엘     727    12     0      9     57     805  2019-01
21        터키     792    13    32     36    912    1785  2019-01
22    우즈베키스탄    1958   561     0    407   2828    5754  2019-01
23     카자흐스탄    2185    24     7     92   1266    3574  2019-01
24       GCC    1550    37    14     72    103    1776  2019-01
25    아시아 기타    1561   308    70    205   2410    4554  2019-01
27        미국   42989   418  2578    229  16523   62737  2019-01
28       캐나다    8034    57    30     43   4296   12460  2019-01
29       멕시코    1282    11     7     38    515    1853  2019-01
30       브라질    1136    16     9     41    403    1605  2019-01
31     미주 기타    1541    24    33    128    540    2266  2019-01
33        영국    7982   175    17     41   1933   10148  2019-01
34        독일    4925   278    19    177   1451    6850  2019-01
35       프랑스    3773   297    48    288   1168    5574  2019-01
36      네덜란드    1592    47    16     77    537    2269  2019-01
37       스웨덴     844    29     6     18     85     982  2019-01
38       스위스     613    18     0     19     97     747  2019-01
39      이탈리아    1968    83    17     40    623    2731  2019-01
40       덴마크     520    21     6     16    188     751  2019-01
41      노르웨이     552    66     4     28    151     801  2019-01
42       벨기에     490    24     4     22    169     709  2019-01
43     오스트리아     544     8     2     13    209     776  2019-01
44       스페인    1010    36    15     52    255    1368  2019-01
45       그리스     481    17     4      0    273     775  2019-01
46      포르투갈     416    14     0     13    121     564  2019-01
47       핀란드     412    23     1     18    405     859  2019-01
48      아일랜드     392    15     1      2    185     595  2019-01
49     우크라이나     593    58     3     28   1580    2262  2019-01
50       러시아   17260   181    37    191   7525   25194  2019-01
51     크로아티아     226    12     0      3    250     491  2019-01
52      루마니아     412     8     4      3    445     872  2019-01
53      불가리아     154     1     1     10    265     431  2019-01
54       폴란드     713    10     0     27    574    1324  2019-01
55     구주 기타    1809    44    25     91    996    2965  2019-01
57   오스트레일리아   12795    93    17     34   1346   14285  2019-01
58      뉴질랜드    2029    20    17      5    654    2725  2019-01
59    대양주 기타     555     3     4      0     52     614  2019-01
61  남아프리카공화국     368     9     1      6    616    1000  2019-01
62   아프리카 기타     768   718    90    206    908    2690  2019-01
64      국적미상      33     4     0      1     16      54  2019-01
66        교포       0     0     0      0  15526   15526  2019-01

In [ ]:
kto_201901_country_newindex = kto_201901_country.reset_index(drop=True)

In [ ]:
kto_201901_country_newindex.head()

    국적      관광    상용   공용  유학/연수    기타       계     기준연월
0   일본  198805  2233  127    785  4576  206526  2019-01
1   대만   86393    74   22    180  1285   87954  2019-01
2   홍콩   34653    59    2     90  1092   35896  2019-01
3  마카오    2506     2    0     17    45    2570  2019-01
4   태국   34004    37  199     96  6998   41334  2019-01

In [ ]:
continents = ['아시아']*25+['아메리카']*5+['유럽']*23+['오세아니아']*3+['아프리카']*2+['기타대륙']+['교포']

In [ ]:
kto_201901_country_newindex['대륙'] = continents

In [ ]:
kto_201901_country_newindex.head()

    국적      관광    상용   공용  유학/연수    기타       계     기준연월   대륙
0   일본  198805  2233  127    785  4576  206526  2019-01  아시아
1   대만   86393    74   22    180  1285   87954  2019-01  아시아
2   홍콩   34653    59    2     90  1092   35896  2019-01  아시아
3  마카오    2506     2    0     17    45    2570  2019-01  아시아
4   태국   34004    37  199     96  6998   41334  2019-01  아시아

In [ ]:
kto_201901_country_newindex['관광객비율(%)'] = round(kto_201901_country_newindex['관광'] / kto_201901_country_newindex['계'] * 100,1)

In [ ]:
kto_201901_country_newindex.head()

    국적      관광    상용   공용  유학/연수    기타       계     기준연월   대륙  관광객비율(%)
0   일본  198805  2233  127    785  4576  206526  2019-01  아시아      96.3
1   대만   86393    74   22    180  1285   87954  2019-01  아시아      98.2
2   홍콩   34653    59    2     90  1092   35896  2019-01  아시아      96.5
3  마카오    2506     2    0     17    45    2570  2019-01  아시아      97.5
4   태국   34004    37  199     96  6998   41334  2019-01  아시아      82.3

In [ ]:
# 관광객 비율 높은 순으로 5개국가

kto_201901_country_newindex.sort_values(by = '관광객비율(%)').head()

# 관광객 비율 낮은 순으로 5개국가

       국적   관광   상용  공용  유학/연수     기타      계     기준연월   대륙  관광객비율(%)
59     교포    0    0   0      0  15526  15526  2019-01   교포       0.0
14  방글라데시  149  126  27     97    848   1247  2019-01  아시아      11.9
12   스리랑카  157   54   5     28   1043   1287  2019-01  아시아      12.2
13   파키스탄  238  178  10    193    413   1032  2019-01  아시아      23.1
15   캄보디아  635   39  55     51   1915   2695  2019-01  아시아      23.6

In [ ]:
# 관광객 비율 낮은 순으로 5개국가

kto_201901_country_newindex.sort_values(by = '관광객비율(%)', ascending = False).head()

        국적      관광    상용   공용  유학/연수    기타       계     기준연월     대륙  관광객비율(%)
1       대만   86393    74   22    180  1285   87954  2019-01    아시아      98.2
3      마카오    2506     2    0     17    45    2570  2019-01    아시아      97.5
2       홍콩   34653    59    2     90  1092   35896  2019-01    아시아      96.5
0       일본  198805  2233  127    785  4576  206526  2019-01    아시아      96.3
55  대양주 기타     555     3    4      0    52     614  2019-01  오세아니아      90.4

In [ ]:
kto_201901_country_newindex.pivot_table(values = '관광객비율(%)',
                                        index = '대륙',
                                        aggfunc = 'mean')

        관광객비율(%)
대륙
교포      0.000000
기타대륙   61.100000
아메리카   68.200000
아시아    59.624000
아프리카   32.700000
오세아니아  84.833333
유럽     63.826087

In [ ]:
condition  = (kto_201901_country_newindex['국적'] == '중국')
kto_201901_country_newindex[condition]

    국적      관광    상용   공용  유학/연수     기타       계     기준연월   대륙  관광객비율(%)
17  중국  320113  2993  138   8793  60777  392814  2019-01  아시아      81.5

In [ ]:
tourist_sum = sum(kto_201901_country_newindex['관광'])
tourist_sum

884293

In [ ]:
kto_201901_country_newindex

          국적      관광    상용    공용  ...       계     기준연월     대륙 관광객비율(%)
0         일본  198805  2233   127  ...  206526  2019-01    아시아     96.3
1         대만   86393    74    22  ...   87954  2019-01    아시아     98.2
2         홍콩   34653    59     2  ...   35896  2019-01    아시아     96.5
3        마카오    2506     2     0  ...    2570  2019-01    아시아     97.5
4         태국   34004    37   199  ...   41334  2019-01    아시아     82.3
5      말레이시아   19043    95     7  ...   22065  2019-01    아시아     86.3
6        필리핀   14279   211   161  ...   30473  2019-01    아시아     46.9
7      인도네시아   14183   136    38  ...   18842  2019-01    아시아     75.3
8       싱가포르    8372    94     8  ...    9855  2019-01    아시아     85.0
9        미얀마    1304    10    31  ...    5289  2019-01    아시아     24.7
10       베트남   10739   763   110  ...   20183  2019-01    아시아     53.2
11        인도    2318  2656    46  ...    8671  2019-01    아시아     26.7
12      스리랑카     157    54     5  ...    1287  2019-01    아시아     12.2
13      파키스탄     238   178    10  ...    1032  2019-01    아시아     23.1
14     방글라데시     149   126    27  ...    1247  2019-01    아시아     11.9
15      캄보디아     635    39    55  ...    2695  2019-01    아시아     23.6
16        몽골    8358    77   304  ...    9785  2019-01    아시아     85.4
17        중국  320113  2993   138  ...  392814  2019-01    아시아     81.5
18        이란      60    45    10  ...     184  2019-01    아시아     32.6
19      이스라엘     727    12     0  ...     805  2019-01    아시아     90.3
20        터키     792    13    32  ...    1785  2019-01    아시아     44.4
21    우즈베키스탄    1958   561     0  ...    5754  2019-01    아시아     34.0
22     카자흐스탄    2185    24     7  ...    3574  2019-01    아시아     61.1
23       GCC    1550    37    14  ...    1776  2019-01    아시아     87.3
24    아시아 기타    1561   308    70  ...    4554  2019-01    아시아     34.3
25        미국   42989   418  2578  ...   62737  2019-01   아메리카     68.5
26       캐나다    8034    57    30  ...   12460  2019-01   아메리카     64.5
27       멕시코    1282    11     7  ...    1853  2019-01   아메리카     69.2
28       브라질    1136    16     9  ...    1605  2019-01   아메리카     70.8
29     미주 기타    1541    24    33  ...    2266  2019-01   아메리카     68.0
30        영국    7982   175    17  ...   10148  2019-01     유럽     78.7
31        독일    4925   278    19  ...    6850  2019-01     유럽     71.9
32       프랑스    3773   297    48  ...    5574  2019-01     유럽     67.7
33      네덜란드    1592    47    16  ...    2269  2019-01     유럽     70.2
34       스웨덴     844    29     6  ...     982  2019-01     유럽     85.9
35       스위스     613    18     0  ...     747  2019-01     유럽     82.1
36      이탈리아    1968    83    17  ...    2731  2019-01     유럽     72.1
37       덴마크     520    21     6  ...     751  2019-01     유럽     69.2
38      노르웨이     552    66     4  ...     801  2019-01     유럽     68.9
39       벨기에     490    24     4  ...     709  2019-01     유럽     69.1
40     오스트리아     544     8     2  ...     776  2019-01     유럽     70.1
41       스페인    1010    36    15  ...    1368  2019-01     유럽     73.8
42       그리스     481    17     4  ...     775  2019-01     유럽     62.1
43      포르투갈     416    14     0  ...     564  2019-01     유럽     73.8
44       핀란드     412    23     1  ...     859  2019-01     유럽     48.0
45      아일랜드     392    15     1  ...     595  2019-01     유럽     65.9
46     우크라이나     593    58     3  ...    2262  2019-01     유럽     26.2
47       러시아   17260   181    37  ...   25194  2019-01     유럽     68.5
48     크로아티아     226    12     0  ...     491  2019-01     유럽     46.0
49      루마니아     412     8     4  ...     872  2019-01     유럽     47.2
50      불가리아     154     1     1  ...     431  2019-01     유럽     35.7
51       폴란드     713    10     0  ...    1324  2019-01     유럽     53.9
52     구주 기타    1809    44    25  ...    2965  2019-01     유럽     61.0
53   오스트레일리아   12795    93    17  ...   14285  2019-01  오세아니아     89.6
54      뉴질랜드    2029    20    17  ...    2725  2019-01  오세아니아     74.5
55    대양주 기타     555     3     4  ...     614  2019-01  오세아니아     90.4
56  남아프리카공화국     368     9     1  ...    1000  2019-01   아프리카     36.8
57   아프리카 기타     768   718    90  ...    2690  2019-01   아프리카     28.6
58      국적미상      33     4     0  ...      54  2019-01   기타대륙     61.1
59        교포       0     0     0  ...   15526  2019-01     교포      0.0

[60 rows x 10 columns]

In [ ]:
kto_201901_country_newindex['전체비율(%)'] = round(kto_201901_country_newindex['관광'] / tourist_sum * 100, 1)

In [ ]:
kto_201901_country_newindex

          국적      관광    상용    공용  ...     기준연월     대륙  관광객비율(%) 전체비율(%)
0         일본  198805  2233   127  ...  2019-01    아시아      96.3    22.5
1         대만   86393    74    22  ...  2019-01    아시아      98.2     9.8
2         홍콩   34653    59     2  ...  2019-01    아시아      96.5     3.9
3        마카오    2506     2     0  ...  2019-01    아시아      97.5     0.3
4         태국   34004    37   199  ...  2019-01    아시아      82.3     3.8
5      말레이시아   19043    95     7  ...  2019-01    아시아      86.3     2.2
6        필리핀   14279   211   161  ...  2019-01    아시아      46.9     1.6
7      인도네시아   14183   136    38  ...  2019-01    아시아      75.3     1.6
8       싱가포르    8372    94     8  ...  2019-01    아시아      85.0     0.9
9        미얀마    1304    10    31  ...  2019-01    아시아      24.7     0.1
10       베트남   10739   763   110  ...  2019-01    아시아      53.2     1.2
11        인도    2318  2656    46  ...  2019-01    아시아      26.7     0.3
12      스리랑카     157    54     5  ...  2019-01    아시아      12.2     0.0
13      파키스탄     238   178    10  ...  2019-01    아시아      23.1     0.0
14     방글라데시     149   126    27  ...  2019-01    아시아      11.9     0.0
15      캄보디아     635    39    55  ...  2019-01    아시아      23.6     0.1
16        몽골    8358    77   304  ...  2019-01    아시아      85.4     0.9
17        중국  320113  2993   138  ...  2019-01    아시아      81.5    36.2
18        이란      60    45    10  ...  2019-01    아시아      32.6     0.0
19      이스라엘     727    12     0  ...  2019-01    아시아      90.3     0.1
20        터키     792    13    32  ...  2019-01    아시아      44.4     0.1
21    우즈베키스탄    1958   561     0  ...  2019-01    아시아      34.0     0.2
22     카자흐스탄    2185    24     7  ...  2019-01    아시아      61.1     0.2
23       GCC    1550    37    14  ...  2019-01    아시아      87.3     0.2
24    아시아 기타    1561   308    70  ...  2019-01    아시아      34.3     0.2
25        미국   42989   418  2578  ...  2019-01   아메리카      68.5     4.9
26       캐나다    8034    57    30  ...  2019-01   아메리카      64.5     0.9
27       멕시코    1282    11     7  ...  2019-01   아메리카      69.2     0.1
28       브라질    1136    16     9  ...  2019-01   아메리카      70.8     0.1
29     미주 기타    1541    24    33  ...  2019-01   아메리카      68.0     0.2
30        영국    7982   175    17  ...  2019-01     유럽      78.7     0.9
31        독일    4925   278    19  ...  2019-01     유럽      71.9     0.6
32       프랑스    3773   297    48  ...  2019-01     유럽      67.7     0.4
33      네덜란드    1592    47    16  ...  2019-01     유럽      70.2     0.2
34       스웨덴     844    29     6  ...  2019-01     유럽      85.9     0.1
35       스위스     613    18     0  ...  2019-01     유럽      82.1     0.1
36      이탈리아    1968    83    17  ...  2019-01     유럽      72.1     0.2
37       덴마크     520    21     6  ...  2019-01     유럽      69.2     0.1
38      노르웨이     552    66     4  ...  2019-01     유럽      68.9     0.1
39       벨기에     490    24     4  ...  2019-01     유럽      69.1     0.1
40     오스트리아     544     8     2  ...  2019-01     유럽      70.1     0.1
41       스페인    1010    36    15  ...  2019-01     유럽      73.8     0.1
42       그리스     481    17     4  ...  2019-01     유럽      62.1     0.1
43      포르투갈     416    14     0  ...  2019-01     유럽      73.8     0.0
44       핀란드     412    23     1  ...  2019-01     유럽      48.0     0.0
45      아일랜드     392    15     1  ...  2019-01     유럽      65.9     0.0
46     우크라이나     593    58     3  ...  2019-01     유럽      26.2     0.1
47       러시아   17260   181    37  ...  2019-01     유럽      68.5     2.0
48     크로아티아     226    12     0  ...  2019-01     유럽      46.0     0.0
49      루마니아     412     8     4  ...  2019-01     유럽      47.2     0.0
50      불가리아     154     1     1  ...  2019-01     유럽      35.7     0.0
51       폴란드     713    10     0  ...  2019-01     유럽      53.9     0.1
52     구주 기타    1809    44    25  ...  2019-01     유럽      61.0     0.2
53   오스트레일리아   12795    93    17  ...  2019-01  오세아니아      89.6     1.4
54      뉴질랜드    2029    20    17  ...  2019-01  오세아니아      74.5     0.2
55    대양주 기타     555     3     4  ...  2019-01  오세아니아      90.4     0.1
56  남아프리카공화국     368     9     1  ...  2019-01   아프리카      36.8     0.0
57   아프리카 기타     768   718    90  ...  2019-01   아프리카      28.6     0.1
58      국적미상      33     4     0  ...  2019-01   기타대륙      61.1     0.0
59        교포       0     0     0  ...  2019-01     교포       0.0     0.0

[60 rows x 11 columns]

In [ ]:
kto_201901_country_newindex.sort_values('전체비율(%)', ascending=False).head()

    국적      관광    상용    공용  유학/연수  ...       계     기준연월    대륙 관광객비율(%)  전체비율(%)
17  중국  320113  2993   138   8793  ...  392814  2019-01   아시아     81.5     36.2
0   일본  198805  2233   127    785  ...  206526  2019-01   아시아     96.3     22.5
1   대만   86393    74    22    180  ...   87954  2019-01   아시아     98.2      9.8
25  미국   42989   418  2578    229  ...   62737  2019-01  아메리카     68.5      4.9
2   홍콩   34653    59     2     90  ...   35896  2019-01   아시아     96.5      3.9

[5 rows x 11 columns]

In [ ]:
# 위 과정 전체를 함수로 만들자 

1. 데이터 파악(생략)
2. 파이선으로 읽어오기
3. 데이터탐색(생략)
4. 기준년월 컬럼 추가
5. 국적 데이터만 남기기(대륙 합계계산 행 삭제)
6. 대륙 컬럼 만들기 열생성
7. 국적별 관광객 비율 계산 열생성
8. 전체 방문객 대비 국가별 관광객 비율 계산 열생성

In [ ]:
def create_kto_data(yy,mm):
  # 2. 파이선으로 읽어오기
  file_p = 'kto_{}{}.xlsx'.format(yy,mm)

  df = pd.read_excel(file_p,
                           header = 1,
                           usecols = 'A:G',
                           skipfooter=4)
  # 4. 기준년월 컬럼 추가
  df['기준연월'] = '{}-{}'.format(yy,mm)  

  # 5. 국적 데이터만 남기기(대륙 합계계산 행 삭제)
  continents_list = ['아시아주','미주','구주','대양주','아프리카주','기타대륙','교포소계']
  condition = (df['국적'].isin(continents_list)==False)
  df_country = df[condition].reset_index(drop=True)

  # 6. 대륙 컬럼 만들기 열생성
  continents = ['아시아']*25+['아메리카']*5+['유럽']*23+['오세아니아']*3+['아프리카']*2+['기타대륙']+['교포']
  df_country['대륙'] = continents

  # 7. 국적별 관광객 비율 계산 열생성
  df_country['관광객비율(%)'] = round(df_country['관광'] / df_country['계'] * 100,1)

  #8. 전체 방문객 대비 국가별 관광객 비율 계산 열생성
  tourist_sum=sum(df_country['관광'])
  df_country['전체비율(%)'] = round(df_country['관광'] / tourist_sum * 100, 1)

  return(df_country)



kto_test = create_kto_data(2018,12)
kto_test.head()

    국적      관광    상용   공용  유학/연수    기타       계     기준연월   대륙  관광객비율(%)  전체비율(%)
0   일본  252461  1698  161    608  3593  258521  2018-12  아시아      97.7     22.7
1   대만   85697    71   22    266  1252   87308  2018-12  아시아      98.2      7.7
2   홍콩   58355    41    3    208   939   59546  2018-12  아시아      98.0      5.2
3  마카오    6766     0    1     20    36    6823  2018-12  아시아      99.2      0.6
4   태국   47242    42  302     58  6382   54026  2018-12  아시아      87.4      4.2